### ISSUE TITLE
OpenAPI schemas with a default value aren't marked as optional

### ISSUE THREAD

**Issue by mattmess1221** [johannschopplich/nuxt-api-party#72]
### Environment

```
❯ npx nuxi info
Working directory: /home/projects/nuxt-starter-8hsfcz
Nuxt project info:

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      modules, watch, apiParty, devtools
- Runtime Modules:  nuxt-api-party@2.0.0
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-qqitc3?file=nuxt.config.ts

### Describe the bug

Components with a default value and aren't included in the `required` key aren't marked as optional in the resulting typescript declarations.

### Additional context

Input schema:
```yaml
components:
  schemas:
    UserRegistration:
      type: object
      properties:
        name:
          type: string
        age:
          type: number
        subscribe:
          type: boolean
          default: true
      required: [ name ]
```

Output .d.ts
```ts
export interface components {
  schemas: {
    UserRegistration: {
      name: string;
      age?: number;
      /** @default true */
      subscribe: boolean;
    }
  }
}
```
